@startuml
skinparam linetype ortho
partition "Infrastructure Receive" {
(*) -down-> "Input"

partition "HttpRequest" {
    "Input" -down-> "Endpoint"
    "Endpoint" -down-> "HttpMate"
}
"HttpMate" -down-> "Map"
"Map" -down-> "MapMate"
partition "SQS Message" {
    "Input" -down-> "SQS Message"
    "SQS Message" -down-> "AwsSQSApi"
}
"AwsSQSApi" -down-> "Map"
partition "SNS Message" {
    "Input" -down-> "SNS Message"
    "SNS Message" -down-> "AwsSNSApi"
}
"AwsSNSApi" -down-> "Map"
}

partition "Infrastructure Output" {
    "ServiceBus" -left-> "ServiceImpl #1"
    "ServiceImpl #1" -left-> "Twitter API"
    "ServiceBus" -right-> "ServiceImpl #2"
    "ServiceImpl #2" -right-> "Twitter API SNS"
    "Twitter API SNS" -> "SNS Message"
}

partition "Domain" {
    "MapMate" -down-> "UseCaseBus"
    "DomainBus" -down-> "UseCase"
    "UseCase" -right-> "ServiceBus"
}

partition "BrowserTab" {
    "ServiceBus" -up-> "PresenterService"
    "PresenterService" -up-> "WebSocket"
    "WebSocket" -up-> "PopUp Requesting OK/Cancel"
}

@enduml
