@startuml
skinparam linetype ortho

(*) -down-> "HTTPMATE"

(*) -down-> "SQSMATE"

HTTPMATE -down-> "USECASES"
SQSMATE -down-> "USECASES"

USECASES -down-> AUTHORIZER
AUTHORIZER -down-> PREINVOKER
PREINVOKER -down-> INVOKER

@enduml