@startuml
skinparam linetype ortho

(*) -down-> "PRE-PROCESS"
note right
logging, xss
end note

-down-> "PROCESS HEADERS"
note right
mit datentyp HeaderProcessing
gibt HttpMessageBuilder(jwt-Token), nextstep, parameters+source zurück
end note

-down-> "PROCESS BODY"
if "MultiPart" then
    -left->[multipart] "PROCESS MULTIPART"
else
    -right->[defaultAction] "PROCESS SINGLE_PART"
endif
partition "Call Context" {
    "PROCESS SINGLE_PART" -down->[call] "PROCESS BODY STRING"
    if "Content-Type" then
        -down->[json] "UNMARSHALL JSON"
      else
        -down->[xml] "UNMARSHALL XML"
      else
        -down->[yaml] "UNMARSHALL YAML"
      else
        -down->[binary] "PRE-PROCESS BINARY AUTHORIZATION"
         "PRE-PROCESS BINARY AUTHORIZATION" -down-> "PROCESS BINARY"
}
"PROCESS MULTIPART" -down->[call] "PROCESS BODY STRING"
"PROCESS SINGLE_PART" -right-> "DETERMINE EVENT"
"PROCESS MULTIPART" -right-> "DETERMINE EVENT"
"DETERMINE EVENT" -down-> "PRE-MAP TO EVENT"
        note right
            path parameters
        end note
"PRE-MAP TO EVENT" -down-> "AUTHENTICATION"
"AUTHENTICATION" -down-> "MAP TO EVENT"
"MAP TO EVENT" -down-> "SUBMIT"
"SUBMIT" -down-> "DOMAIN BUS"
            note right
                DTO to use case
                authorization
            end note

@enduml
